In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('C:/Users/Budniak Piotr/Documents/Dla_Grzegorza.csv', sep=';', encoding='utf-8')
df.head()

,trakt,NR_PUNKTU,nr_pow,sredni_wiek_buka,gatunek_najliczniejszy_w_1_warstwie
0,6094,60943,3,25,ŚW
1,6097,60971,1,81,BK
2,6162,61624,4,79,BK
3,6165,61654,4,82,BK
4,7158,71582,2,133,BK

In [20]:
df = df[df.gatunek_najliczniejszy_w_1_warstwie == "BK"]

In [24]:
df

,trakt,NR_PUNKTU,nr_pow,sredni_wiek_buka,gatunek_najliczniejszy_w_1_warstwie
1,6097,60971,1,81,BK
2,6162,61624,4,79,BK
3,6165,61654,4,82,BK
4,7158,71582,2,133,BK
5,7158,71585,5,109,BK
...,...,...,...,...,...
790,148065,1480654,4,72,BK
791,148065,1480655,5,47,BK
792,149065,1490651,1,48,BK
793,151064,1510642,2,69,BK
794,152062,1520624,4,112,BK

In [25]:
collection = []

for i, group in df.groupby('trakt'):
    if 3 in group['nr_pow'].values:
        collection.append(group.loc[group['nr_pow'] == 3])
    elif 4 in group['nr_pow'].values:
        collection.append(group.loc[group['nr_pow'] == 4])
    elif 2 in group['nr_pow'].values:
        collection.append(group.loc[group['nr_pow'] == 2])
    elif 5 in group['nr_pow'].values:
        collection.append(group.loc[group['nr_pow'] == 5])
    elif 1 in group['nr_pow'].values:
        collection.append(group.loc[group['nr_pow'] == 1])

In [26]:
pd.concat(collection, axis=0).to_excel('C:/Users/Budniak Piotr/Documents/Dla_Grzegorza_propozycje_pow_tylko_BK_pan.xlsx', index=False)